/*
 * LED_SYSTEM_interface.h
 *
 *  Created on: Mar 19, 2022
 *      Author: Tarek ElDallal
 */

#ifndef HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_CONFIG_H_
#define HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_CONFIG_H_

#define LED_SYSTEM_PORT 		DIO_u8_tPORT_B
#define LED_SYSTEM_PIN			DIO_u8_tPIN0



#endif /* HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_CONFIG_H_ */
