/*
 * LED_SYSTEM_interface.h
 *
 *  Created on: Mar 19, 2022
 *      Author: Tarek ElDallal
 */

#ifndef HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_PRIVATE_H_
#define HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_PRIVATE_H_



#endif /* HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_PRIVATE_H_ */
